color_number = dict(
    ENDC=0,
    RED=31,
    GREEN=32,
    GOLD=33,
    BLUE=34,
    PURPLE=35,
    LIGHTBLUE=36,
    GRAY=37,
    RED_BG=41,
    GREEN_BG=42,
    GOLD_BG=43,
    BLUE_BG=44,
    PURPLE_BG=45,
    LIGHTBLUE_BG=46,
    GRAY_BG=47,
    DARKGRAY_SOFT=90,
    RED_SOFT=91,
    GREEN_SOFT=92,
    GOLD_SOFT=93,
    BLUE_SOFT=94,
    PURPLE_SOFT=95,
    LIGHTBLUE_SOFT=96,
    GRAY_SOFT=97,
    DARKGRAY_SOFT_BG=100,
    RED_SOFT_BG=101,
    GREEN_SOFT_BG=102,
    GOLD_SOFT_BG=103,
    BLUE_SOFT_BG=104,
    PURPLE_SOFT_BG=105,
    LIGHTBLUE_SOFT_BG=106,
    GRAY_SOFT_BG=107,
    HEADER=95,
    OKBLUE=94,
    OKGREEN=92,
    WARNING=93,
    FAIL=91,
    BOLD=1,
    UNDERLINE=4,
    CROSSOUT=28,
    GRYHIGHLT=7,
    BLACKBLACK=30)

colors_dict = {k: '\033[%dm' % v for k, v in color_number.items()}

if __name__ == '__main__':
    print(colors_dict['RED'], 'This is red', colors_dict['ENDC'])
